### ISSUE TITLE
Reconstruct input signal from LegS coefficients?

### ISSUE THREAD

**Issue by chifenggengmengyue** [HazyResearch/hippo-code#6]
Hi, Sorry to bother again. As metioned in issue #5  I was trying to reconstruct the input signal using 'hippo_legs.reconstruct' method in model/hippo.py as follows:
N=200
L=100
hippo_legs = HiPPO_LegS(N)
x = torch.randn(L, 1)                                       # random input signal
y = hippo_legs(x)                                            # legS coefficients, size [200,1,100]
x_rec = hippo_legs.reconstruct(y)                  # reconstruction result,  size [200,1,1024], 1024 is the default max_seq_len
mse = mse_loss(x.squeeze(), x_rec[-1,0,0:L])  # returns mse=tensor(1.4863)

The numerical result in 'x_rec' is quite different from 'x'.

After checking the 'vals' and 'eval_matrix' in L#93-94 in hippo.py I see the code assumes the input in [0,1], and uses basis functions g_n(t,x) with t=1.0 for all 200 coeff sets.

My problems are:
1, What is wrong with my reconstruction procedure? As shown in the paper the mse should be pretty small. Any example for reconstructing 'x'?
2, Why use g(t,x) with t=1.0 for all coeff sets? My understanding of the paper is to use different t for each coeff set in order to perform online approximation?

Many thanks!

**Comment by chifenggengmengyue** [comment]
I have triple-checked the whole process from A to Z, taking pages of notes, but still have no clue...Can anybody shed some light on this? The code seems perfectly matches the theory in paper.

**Comment by albertfgu** [comment]
Hi, My apologies, I didn't see this question until now.

I have just tested the code and it works. I updated the hippo.py file with plotting code using smooth functions that recreates our experiment (Figure 3).

To answer your questions:
- First, I believe you should not be using `x_rec[-1,0,0:L]` (the first L points), but instead L uniformly spaced points. Conceptually, you are feeding in a discrete sequence of length L that HiPPO thinks represents a continuous function between [0,1]. It is then reconstructing the continuous function using 1024 (uniformly spaced) nodes. So for example if L=100 and max_length=1000, then you should use `x_rec[-1,0,::max_length//L]`
- To make things easier, you can just always pass in `HiPPO_LegS(N, max_length=L)` to ensure that things line up
- with that said, the reconstruction is not guaranteed to be perfect; you're passing in a discrete sequence of completely random noise, which is not easily represented as a continuous function. Note Proposition 6 in the paper, which says that the error rate depends on the smoothness of the function, which makes intuitive sense

Apologies again for the slow response and any difficulties this may have caused. For more math questions, feel free to email me directly.

**Comment by chifenggengmengyue** [comment]
Thanks! No difficulties caused :) I definitely enjoyed walking through the code and those beautiful equations. I am not an expert in math and that indeed causes trouble...Thanks again for the detailed response and warm feedback...

**Comment by albertfgu** [comment]
No problem! If you don't mind, please leave this issue open for a little bit as I want to return (after a deadline this week) to clean up and document the reconstruction code to make it a little easier for people to understand and use. Thanks for pointing these out!

**Comment by makarr** [comment]
Instead of starting a new issue I thought I'd add on to this one, since it's related.  If I pass `measure='legt'` instead of `measure='lmu'` to the `HiPPO_LegT` constructor in `hippo.plot()`, then the reconstruction error is orders of magnitude worse.  Why is this?  The `lagt` variants also perform very poorly.

Thanks.

**Comment by albertfgu** [comment]
Hi @makarr,

I've updated the experiment file and the documentation at the top.
In brief, that measure argument should not be configurable and has been removed from the interface. Each HiPPO method is composed of one particular measure and polynomial basis, and these are linked. In other words the `HiPPO_LegT` module is performing function reconstruction using one particular polynomial basis ("translated Legendre"), which corresponds to one particular measure.

One other question you may have is why is the measure `lmu` instead of `legt`. The reason is that these two measures/methods are exactly the same up to a normalization constant. In fact, HiPPO was motivated to generalize the LMU, and the HiPPO-LegT instance of HiPPO is the one that captures LMU (up to a constant). The reason the 'lmu' measure is used is that this corresponds to the default scipy polynomials (the `ss.eval_legendre` call in this module), which are the unnormalized Legendre polynomials, whereas 'legt' (and all HiPPO methods) use the normalized orthogonal polynomials.
